# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-22 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busarrivalv2',
            old_name='latitue',
            new_name='latitude',
        ),
        migrations.RemoveField(
            model_name='busarrivalv2',
            name='logitute',
        ),
    ]
