# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_busarrivalv2_last_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busarrivalv2',
            name='bus_stop_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
