# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_busarrivalv2_bus_stop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='busTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_bus', models.TextField()),
                ('next_bus1', models.TextField()),
                ('next_bus2', models.TextField()),
                ('busarrivalv2_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analytics.busarrivalv2')),
            ],
        ),
    ]
